### ISSUE TITLE
Add information/requirements to screenshot/README.md

### ISSUE THREAD

**Issue by tanuj101** [tanuj101/awesome-dmenu#5]

**Comment by Kvaibhav01** [comment]
I would like to work on this. Let me know the information/requirements so that I can add them to Readme file.

**Comment by tanuj101** [comment]
@Kvaibhav01 just try running the script you'd get the information i.e. what it can do maybe add a screenshot or something like that. By reading the code you'd see the programs the script is using just mention them

**Comment by tanuj101** [comment]
#8 closes
